# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=250)),
                ('year_released', models.DateField(max_length=8)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='core.MyUser')),
                ('song', models.ManyToManyField(related_name='playlist', to='songs.Song')),
            ],
        ),
    ]
