# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=250)),
                ('year_released', models.DateField(max_length=8)),
                ('track', models.ManyToManyField(related_name='album', to='songs.Song')),
            ],
        ),
    ]
